<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="<?= BASE_URI; ?>/css/reset.css" />
	<link rel="stylesheet" href="<?= BASE_URI; ?>/css/screen.css" />
    <link rel="stylesheet" href="<?= LEAFLET;  ?>/leaflet.css" />
    <script src="<?= LEAFLET; ?>/leaflet.js"></script>
	<title><?php echo isset($this->title) ? self::escape($this->title) : APPLICATION_NAME; ?></title>

</head>
